### ISSUE TITLE
Manque l'activation de certains process

### ISSUE THREAD

**Issue by gheleguen** [KonkArLab/kosmos_software#11]
Afin de lancer le script du KOSMOS, il est nécéssaire d'activer quelques outils dans la config de la raspberry. 

Pour accéder à la config, entrer : ```sudo raspi-config```

Puis dans le troisième menu passer en enable les objets suivants : 

- Legacy camera
- I2C
- ssh

**Comment by UpsylonDev** [comment]
hello ;-)  oui il faudrait rajouter ça dans le bash d'install...

**Comment by KonkArLab** [comment]
problème corrigé dans la version 2023
