### ISSUE TITLE
Problème de chemin dans csv.py et cam.py

### ISSUE THREAD

**Issue by KonkArLab** [KonkArLab/kosmos_software#15]
Bonjour, 
J'ai réussis à lancer KOSMOS 2 tout à l'heure. 
Il m'a fallu modifier des chmins dans le programme python 
 - kosmos_csv.py
 - kosmos_cam.py
Il y a une méthode très étrange pour naviguer dans l'arborescence. 

Il me semble aussi avoir modifié le chemin dans kosmos_find_usb.py et kosmos_config.sh

**Comment by AmauMaill** [comment]
As-tu utilisé le code sur la branche main ou le code sur ma branche ?

**Comment by UpsylonDev** [comment]
la lib tree est installée : ce qui permet de voir l'arbo plus clairement il faut faire>   tree  -L 1
(L pour level de profondeur d'affichage ) 
https://www.geeksforgeeks.org/tree-command-unixlinux/ 
;-)

**Comment by KonkArLab** [comment]
problème corrigé dans la version 2023
