### ISSUE TITLE
dev_Amaury : 1er essai sur KOSMOS

### ISSUE THREAD

**Issue by KonkArLab** [KonkArLab/kosmos_software#17]
Bonjour, 
J'ai lancé le script d'install tout est ok.
Puis rebooté
Modifié sur la clés usb le config.ini

Puis j'ai lancé le script lancement  : 
`.kosmos_software/lancement.sh`

Le script démarre mais bloque. Il ne traouvait pas le lien pour monter la clé usb.
J'ai donc ajouté dans lancement.sh après mkdir un p soit `mkdir -p`

Désormais le script bloque à quelquechose que je ne connais pas. Voilà le retour : 
`File "/home/kosmos3/kosmos_software/src/config.py", line 11, in <module>
      CONF_FILE = environ("CONF_FILE")
TypeError : '_Environ' object is not callable`

## Il reste une erreur aussi sur l'horlage RTC mais que l'on peut fixer par une manip : 

Voilà donc ce que j'ai du faire :

Installation de I2c-tools
`sudo apt-get install i2c-tools`

Recherche du port de l'horloge
`sudo i2cdetect -y 1`

On peut répéter cette oppération avec et sans la connexion au capteur de pression. Ainsi on s'assure d'avoir le bon port. Ici j'obtien le canal 68 pour l'horloge et 76 pour le capteur de pression.
Notifier le nouveau composant installé au système :
`echo ds3231 0x68 | sudo tee /sys/class/i2c-adapter/i2c-1/new_device`
Cette dernière commande n'a pas fonctionné de suite. Il a fallu que je change les droits d'écritures sur /sys et le dossier new_device.

**Comment by AmauMaill** [comment]
#18
